const commands = [
    {
      category: "Economy Commands",
      list: [
        { name: "ដាក់លុយ - Dakluy", description: "ដាក់លុយចូលធនាគារ", example: "Tdak [ចំនួនលុយ]" },
        { name: "ដកលុយ - Dokluy", description: "ដកលុយធនាគារ", example: "Tdok [ចំនួនលុយ]" },
        { name: "លុយ - Luy", description: "បង្ហាញលុយរបស់អ្នក", example: "Tluy" },
        { name: "ធនាគារ - Bank", description: "ឆែកលុយធនាគារ", example: "Tbank" },
        { name: "LeaderBoard", description: "បង្ហាញអ្នកមានលុយច្រើន", example: "Tlb" },
        { name: "Hi", description: "បង្ហាញលុយទាំងអស់", example: "Thi" },
        { name: "Daily", description: "រកលុយប្រចាំថ្ងៃ", example: "Tdaily" },
        { name: "អោយ - Oy", description: "អោយលុយគេ", example: "Toy @mention [ចំនួនលុយ]" },
        { name: "ត្រី - Fish", description: "ស្ទួចត្រីយកលុយ", example: "Tfish" },
        { name: "ប្លន់ - Plon", description: "ប្លន់លុយគេ", example: "Tplon @mention" },
        { name: "សុំលុយ - Somluy", description: "សុំលុយbot", example: "Tsomluy" },
        { name: "ហេក - Hack", description: "Hack ប្រអប់យកលុយ", example: "Thack" },
        { name: "Spin", description: "បង្វិលយកលុយ", example: "Tspin" },
        { name: "Weekly", description: "យកលុយរាល់អាទិត្យ", example: "Tweekly" },
        { name: "ធ្វើការ - Tverka", description: "ធ្វើការយកលុយ", example: "Twork" },
        { name: "Thumnail", description: "កន្លែងទិញ Thumnail", example: "Tn" },
        { name: "Background", description: "ទិញ Backgroud សម្រាប់ profile", example: "Tbg" },
        { name: "Item", description: "ទិញ item", example: "Titem 1"}
      ],
    },
    {
      category: "Game Commands",
      list: [
        { name: "Flip", description: "បង្វិលកាក់ទាញថាចេញក្បាលរឺកន្ទុយ", example: "Tflip [ចំនួនលុយ] [H រឺ T]" },
        { name: "Slot", description: "បង្វិលតាមសំណាង", example: "Tjak [ចំនួនលុយ]" },
        { name: "ប៊ូតុង - Button", description: "ហ្គេមពីរអ្នករកអ្នកចុចបានពណ័បៃតងច្រើនជាងគេ", example: "Tbt @mention" },
        { name: "MLBB", description: "ទាយឈ្មោះ Hero ក្នុង​ MLBB", example: "Thm" },
        { name: "Find Emoji", description: "មើលអោយចាំហើយត្រូវរើសថារូបនឹងនៅទីណា", example: "Tfe" },
        { name: "Connect Four", description: "ហ្គេមពីរអ្នកលេងបានបួនជាប់គ្នាឈ្នះ", example: "Tc4 @mention" },
        { name: "ប៉ក់ក្តាំង - Cp", description: "លេងប៉ក់ក្តាំងបានបួនអ្នកចុះ", example: "Tcp [ចំនួនលុយ]" },
        { name: "បាល់ - Ball", description: "ហ្គេមទាត់បាល់", example: "Tball [ចំនួនលុយ]" },
        { name: "ខ្លាឃ្លោក - Kk", description: "ចាក់ខ្លាឃ្លោកលេងបានប្រាំអ្នកចុះ", example: "Tkk [ចំនួនលុយ]" },
        { name: "ឡុកឡាក់ - Ll", description: "ចាក់ឡុកឡាក់", example: "Tll [ចំនួនលុយ]" },
        { name: "គណិត - Math", description: "ហ្គេមពីរអ្នករកអ្នកគិតលេខលឿន", example: "Tmath @mention" },
        { name: "Number", description: "ទាយលេខលេងបានបីអ្នកចុះ", example: "Tgn @mention" },
        { name: "ប៉ាវ - Pav", description: "លេងប៉ាវពីរអ្នកក៏បានម្នាក់ឯងក៏បាន", example: "Tpav @mention" },
        { name: "ពាក្យ - Peak", description: "ហ្គេមពីរអ្នកណាគេសរសេរលឿនឈ្នះ", example: "Tpeak @mention" },
        { name: "ក្រាស់ស្តើង - Cs", description: "ទាយថាចេញក្រាស់រឺស្តើង", example: "Tsc [ចំនួនលុយ] [s រឺ c]" },
        { name: "Xo", description: "លេងXOពីរអ្នករឺBot", example: "Txo @mention" },
      ],
    },
    {
      category: "Fun Commands",
      list: [
        { name: "បេះដូង - Besdong", description: "ឆែកបេះដូងស្មោះរឺសាវ៉ា", example: "Tbesdong @mention" },
        { name: "Cute", description: "តើអ្នកCuteបុន្មាន%", example: "Tcute @mention" },
        { name: "ដៀល - Deal", description: "សម្រាប់ដៀលគេ", example: "Tdeal @mention" },
        { name: "Emoji", description: "សរសេរពាក្យរឺឈ្មោះ", example: "Temoji [ពាក្យ]" },
        { name: "Favfood", description: "ចូលចិត្តញុាំអី?", example: "Tfavfood @mention" },
        { name: "Favsong", description: "មើលថាចូលចិត្តស្តាប់អ្វី", example: "Tfavsong @mention" },
        { name: "ទម្លាប់ - Habit", description: "ទម្លាប់ប្រចាំថ្ងៃជាអ្វី", example: "Thabit @mention" },
        { name: "កាច - Kach", description: "មើលកាចប៉ុន្មាន%", example: "Tkach @mention" },
        { name: "ត្រូវជា - Jea", description: " ឆែកមើលគេត្រូវជាអីនឹងយើង", example: "Tjea @mention" },
        { name: "ចប់នៅ - Jobnv", description: "សួរគេមើលចប់នៅ", example: "Tjobnv @mention" },
        { name: "ឆ្គួត - Jkut", description: "មើលគេឆ្គួតប៉ុន្មាន%", example: "Tjkut @mention" },
        { name: "គូរ - Ku", description: "ស្វែងរកគូរព្រេង", example: "Tku @mention" },
        { name: "លួង - Loung", description: "លួងនរណាម្នាក់", example: "Tloung" },
        { name: "ញ៉ែ - Nhea", description: "ទុកញ៉ែគេ", example: "Tnhea @mention" },
        { name: "និយាយ - yy", description: " អោយBotនិយាយពាក្យជំនួស", example: "Tyy [ពាក្យ]" },
        { name: "ស្រលាញ់ - Sl", description: "ស្រលាញ់គេប៉ុន្មាន%", example: "Tsl @mention" },
        { name: "សុំ - Som", description: "សុំអ្វីមួយរឺសុំស្រលាញ់នរណាម្នាក់", example: "Tsom [ពាក្យ/@mention]" },
        { name: "Sweet", description: "ឆែកមើលគេចេះsweetអត់", example: "Tsweet @mention" },
        { name: "ខ្វិល - Kjel", description: "មើលថាខ្ចិលពិនណា", example: "Tkjel @mention" },
        { name: "សង្សារ - Ss", description: "មានសង្សារប៉ុន្មានអ្នក", example: "Tss @mention" },
      ],
    },
    {
      category: "Picture Commands",
      list: [
        { name: "អារម្មណ៍ - Arom", description: "មើលអារម្មណ៍យើងសេដប៉ុន្មានសប្បាយប៉ុន្មាន", example: "Tarom @mention" },
        { name: "Avatar", description: "ឆែកមើល Profile", example: "Tav @mention" },
        { name: "ឆ្មាថា - Chmatha", description: "សរសេរពាក្យឆ្មានិយាយតាម", example: "Tchmayy [ពាក្យ]" },
        { name: "លុប - Delete", description: "លុបម្នាក់នឹងចោល", example: "Tdelete @mention" },
        { name: "ចោ - Joa", description: "រូបភាពឧក្រិដ្ឋជន", example: "Tjao @mention" },
        { name: "គុក - Kok", description: "ដាក់ចូលគុក", example: "Tkok @mention" },
        { name: "Meme", description: "ចេញរូបmemeជាមួយពាក្យដែលយើងសរសេរ", example: "Tmeme [ពាក្យ] / [ពាក្យ]" },
        { name: "អត់ច្បាស់ - Otjbas", description: "ធ្វើអោយរូបអត់ច្បាស់", example: "Totjbas @mention" },
        { name: "Pat", description: "ដើម្បីវ៉ែក្បាល", example: "Tpat @mention" },
        { name: "Rainbow", description: "រូបភាពមាន7ពណ័", example: "Trainbow @mention" },
        { name: "Imposter", description: "គេសង្ស័យជា imposter", example: "Timposter @mention" },
        { name: "RIP", description: "បង្ហាញមូលហេតុដែល RIP", example: "Trip @mention" },
        { name: "ស្អាត - Sart", description: "សរសើរគេស្អាត", example: "Tsart @mention" },
        { name: "សត្វ -Sat", description: "បង្ហាញរូបសត្វដែលមានក្នុងបញ្ចី", example: "Tsat [ឈ្មោះសត្វ]" },
        { name: "Ship", description: "ដាក់ ship គេ", example: "Tship @mention @mention" },
        { name: "Sign", description: "លើកផ្លាកដែលយើងសរសេរ", example: "Tsign [ពាក្យ]" },
        { name: "ទាញ", description: "ទាញរូបគេដូចកៅស៊ូ", example: "Tteanh @mention" },
        { name: "Eyya", description: "មេចងាកមើលក្រោយចឹង", example: "Teyya @mention 3អ្នក" },
        { name: "លាយ - Leay", description: "លាយរូបពីរអ្នក", example: "Tleay @mention @mention" },
      ],
    },
    {
      category: "Action Commands",
      list: [
        { name: "ឆ្លាត - Chlat", description: "អង្អែលក្បាលគេ", example: "TChlat @mention" },
        { name: "អៀន - Ean", description: "អៀននរណាម្នាក់", example: "Tean @mention" },
        { name: "អោប - Hug", description: "អោបនរណាម្នាក់", example: "Thug @mention" },
        { name: "កាប់ - Kab", description: "ដេញកាប់គេ", example: "Tkab @mention" },
        { name: "ខាំ - Kham", description: "ខាំមនុស្ស", example: "Tkham @mention" },
        { name: "ខឹង - Khg", description: "ខឹងម្នាក់នោះ", example: "Tkhg @mention" },
        { name: "ទាត់ - Kick", description: "ទាត់គេលេង", example: "Tkick @mention" },
        { name: "សម្លាប់ - Kill", description: "ចង់សម្លាប់នរណាម្នាក់", example: "Tkill @mention" },
        { name: "ថើប - Kiss", description: "ថើបមនុស្សដែលយើងស្រលាញ់", example: "Tkiss @mention" },
        { name: "Morning", description: "អរុណ​សួស្តី", example: "Tmorning" },
        { name: "នឹក - Nerk", description: "នឹកគេ", example: "Tnerk @mention" },
        { name: "អរគុណ - Rkun", description: "អរគុណគេ", example: "Trkun @mention" },
        { name: "Sad", description: "ពេលយើងកំសត់", example: "Tsad" },
        { name: "សប្បាយ - Sby", description: "ពេលយើងសប្បាយ", example: "Tsby" },
        { name: "ដេក - Sleep", description: "ពេលចូលគេង", example: "Tdek" },
        { name: "សុំទោស - Somtus", description: "ពេលចង់សុំទោសគេ", example: "Tsomtus @mention" },
        { name: "ស្រែក - Srech", description: "ស្រែកដាក់អ្នកខ្លះ", example: "Tsrech @mention" },
        { name: "វ៉ៃ - Vaii", description: "ចង់វ៉ែនរណាម្នាក់", example: "Tvai @mention" },
        { name: "យំ - Yum", description: "ពេលយើងចូលតួរ", example: "Tyum" },
        { name: "បាញ់ - Banh", description: "យកកាំភ្លើងបាញ់គេ", example: "Tbanh @mention" },
        { name: "ជ្រេញ - Jrenh", description: "ជ្រេញអ្នកខ្លះ", example: "Tjrenh @mention" },
        { name: "ហោះ - Hus", description: "មើលពីមូលហេតុហោះ", example: "Thus" },
        { name: "ប្រកាច់ - Pkach", description: "ស្ថានភាពប្រកាច់", example: "Tpkach" },
        { name: "ឌឺ - Due", description: "ឌឺគេ", example: "Tbleh @mention" },
      ],
    },
    {
      category: "More Commands",
      list: [
        { name: "Emojitangos", description: "បង្ហាញEmojiទាំងអស់ក្នុងserver", example: "Temojitangos" },
        { name: "Tgw", description: "ដាក់giveaway", example: "Tgw 1h 10 100M" },
        { name: "Help", description: "មើលcommandsទាំងអស់", example: "Thelp" },
        { name: "Rubserver", description: "មើល Profile Sever", example: "Trubserver" },
        { name: "Serverinfo", description: "មើលព័ត៍មានServer", example: "Tserverinfo" },
        { name: "User", description: "មើលព័ត៍មានអ្នក", example: "Tuser" },
        { name: "Prefix", description: "ដាក់ prefix", example: "Thelp" },
        { name: "រៀបការ - Reapka", description: "រៀបការ", example: "Treapka @mention" },
        { name: "លែងលះ - Lglas", description: "លែងលះ", example: "Tlglas" },
        { name: "អាយុ - Age", description: "ដាក់អាយុ", example: "Tage 168" },
        { name: "Birthday", description: "ដាក់BD", example: "Tbd 31 feb" },
        { name: "Facebook", description: "ដាក់fb", example: "Tfb" },
        { name: "Nickname", description: "ដាក់ឈ្មោះ", example: "Tname TheMixz" },
        { name: "ភេទ - Phet", description: "ដាក់ភេទ", example: "Tgender girl" },
        { name: "Profile", description: "ឆែកProfile", example: "Tpf" },
        { name: "Game", description: "មើលហ្គេមទាំងអស់", example: "Tgame" },
        { name: "Ping", description: "មើលping bot", example: "Tping" },
        { name: "Uptime", description: "មើលBot online បានប៉ុន្មានម៉ោង", example: "Tuptime" },
      ],
    },
  ];
  